import Footer from "@/components/Footer/Footer";

export default function UserPolicy() {
  return (
    <div>
      <div className="max-w-4xl mx-auto p-6 bg-white shadow-lg rounded-lg bg-gradient-to-r from-indigo-50 to-sky-50">
        <h1 className="text-2xl font-bold text-gray-900 mb-4">
          User Policy
        </h1>
        <p className="text-gray-700 mb-4">
          Last updated: March 31, 2025
        </p>
        <p className="text-gray-700 mb-4">
          This User Policy describes Our policies and procedures on the
          collection, use, and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law protects
          You.
        </p>
        <p className="text-gray-700 mb-4">
          We use Your Personal data to provide and improve the Service. By using
          the Service, You agree to the collection and use of information in
          accordance with this User Policy. This Privacy Policy has been created
          with the help of the Free Privacy Policy Generator.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          Interpretation and Definitions
        </h2>
        <h3 className="text-lg font-semibold text-gray-800 mt-4">
          Interpretation
        </h3>
        <p className="text-gray-700 mb-4">
          The words of which the initial letter is capitalized have meanings defined
          under the following conditions. The following definitions shall have the same
          meaning regardless of whether they appear in singular or plural.
        </p>

        <h3 className="text-lg font-semibold text-gray-800 mt-4">
          Definitions
        </h3>
        <p className="text-gray-700 mb-4">
          For the purposes of this Privacy Policy:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Application</strong> refers to Bi User, the software program provided by the Company.</li>
          <li><strong>Company</strong> refers to Bi User.</li>
          <li><strong>Country</strong> refers to: Kerala, India</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Application.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          1. Collecting and Using Your Personal Data
        </h2>
        <h3 className="text-lg font-semibold text-gray-800 mt-4">
          Types of Data Collected
        </h3>
        <p className="text-gray-700 mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.</p>

        <h3 className="text-lg font-semibold text-gray-800 mt-4">
          Personal Data
        </h3>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>

        <h3 className="text-lg font-semibold text-gray-800 mt-4">
          Usage Data
        </h3>
        <p className="text-gray-700 mb-4">
          Usage Data is collected automatically when using the Service and may include information such as Your Device&apos;s IP address, browser type, browser version, pages visited, time spent on pages, and other diagnostic data.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          2. Use of Your Personal Data
        </h2>
        <p className="text-gray-700 mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account.</li>
          <li>For the performance of a contract.</li>
          <li>To contact You by email, SMS, or push notifications.</li>
          <li>For business transfers.</li>
          <li>For data analysis and improving our Service.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          3. Sharing and Disclosure of Your Personal Data
        </h2>
        <p className="text-gray-700 mb-4">
          We may share Your personal information in the following situations:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li>With Service Providers.</li>
          <li>For business transfers.</li>
          <li>With Affiliates.</li>
          <li>With business partners.</li>
          <li>With other users (when interacting in public areas).</li>
          <li>With Your consent.</li>
        </ul>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          4. Retention of Your Personal Data
        </h2>
        <p className="text-gray-700 mb-4">
          The Company will retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          5. Security of Your Personal Data
        </h2>
        <p className="text-gray-700 mb-4">
          We strive to use commercially acceptable means to protect Your Personal Data, but remember that no method of transmission over the Internet is 100% secure.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          6. Changes to This Privacy Policy
        </h2>
        <p className="text-gray-700 mb-4">
          We may update this User Privacy Policy from time to time. Any changes will be posted here and you will be notified via email.
        </p>

        <h2 className="text-xl font-semibold text-gray-800 mt-6">
          7. Contact Us
        </h2>
        <p className="text-gray-700 mb-4">
          If you have any questions about this Privacy Policy, you can contact us at{" "}
          <span className="font-semibold"> privacy@brandsinfo.com</span> or visit our website at{" "}
          <a href="https://brandsinfo.in/" className="text-blue-500">https://brandsinfo.in/</a>.
        </p>
      </div>
      <Footer />
    </div>
  );
}
